#Emulicious settings file
#Mon Oct 05 13:42:25 PDT 2026
OutlineWidth=268
GameBoyErrorBreakpointSuspend19=false
GameBoyErrorBreakpointSuspend18=false
GameBoyErrorBreakpointSuspend17=false
GameBoyErrorBreakpointSuspend16=false
WindowEmuliciousWidth=300
GameBoyErrorBreakpointSuspend10=true
GameBoyErrorBreakpointCondition48=
DebuggerMemorySelectedTab=CPU
GameBoyErrorBreakpointCondition9=
GameBoyErrorBreakpointCondition8=
GameBoyErrorBreakpointCondition7=
GameBoyErrorBreakpointCondition6=
BankSwapAtPCBreakpointSuspend=true
GameBoyErrorBreakpointCondition5=
GameBoyErrorBreakpointCondition4=
DataExecutionBreakpointCondition=
GameBoyErrorBreakpointCondition3=
GameBoyErrorBreakpointCondition2=
GameBoyErrorBreakpointCondition1=
DataExecutionBreakpointEnabled=true
GameBoyErrorBreakpointCondition0=
WindowDebuggerWidth=1483
UninitializedMemoryBreakpointSuspend=true
GameBoyErrorBreakpointEnabled48=false
DebuggerConsoleLogBreakpoints=true
GameBoyErrorBreakpointMessage48=
DebuggerHideToolbar=false
DebuggerHideCpuUsageGraph=false
BankSwapAtPCBreakpointCondition=
Update=2
GameBoyErrorBreakpointMessage9=
GameBoyErrorBreakpointMessage8=
GameBoyErrorBreakpointMessage7=
DebuggerSouthPanelSelectedTab=0
GameBoyErrorBreakpointMessage6=
GameBoyErrorBreakpointMessage5=
GameBoyErrorBreakpointMessage4=
GameBoyErrorBreakpointMessage3=
GameBoyErrorBreakpointMessage2=
GameBoyErrorBreakpointMessage1=
GameBoyErrorBreakpointMessage0=
InterruptBreakpointEnabled=true
StackRomWriteBreakpointEnabled=true
StackWidth=1199
GameBoyErrorBreakpointCondition20=
DataExecutionBreakpointSuspend=true
UninitializedMemoryBreakpointCondition=
GameBoyErrorBreakpointSuspend48=false
SouthPanelHeight=633
WindowDebuggerOpen=false
Recent0=D\:\\Apps\\coding projects\\gameboy\\checkers\\main.gb
GameBoyErrorBreakpointCondition19=
GameBoyErrorBreakpointCondition18=
GameBoyErrorBreakpointCondition17=
GameBoyErrorBreakpointCondition16=
GameBoyErrorBreakpointCondition10=
GameBoyErrorBreakpointEnabled20=false
DebuggerWestPanelSelectedTab=0
AudioSync=false
InterruptBreakpointCondition=
GameBoyErrorBreakpointMessage20=
FontSize=13
StackSplitLocation=-1
WindowDebuggerHeight=977
GameBoyErrorBreakpointEnabled19=false
BankSwapAtPCBreakpointEnabled=true
GameBoyErrorBreakpointEnabled18=false
GameBoyErrorBreakpointEnabled17=false
CodeFontSize=13
DebuggerMemoryTabVisibleRect=0,0,0,0
InterruptBreakpointSuspend=true
GameBoyErrorBreakpointEnabled16=false
StackRomWriteBreakpointSuspend=true
GameBoyErrorBreakpointMessage19=
GameBoyErrorBreakpointMessage18=
GameBoyErrorBreakpointMessage17=
GameBoyErrorBreakpointEnabled10=true
GameBoyErrorBreakpointMessage16=
StackRomWriteBreakpointCondition=
WindowEmuliciousHeight=300
GameBoyErrorBreakpointMessage10=
GameBoyErrorBreakpointSuspend9=false
Scale=1.5
GameBoyErrorBreakpointSuspend8=false
GameBoyErrorBreakpointSuspend7=false
GameBoyErrorBreakpointSuspend6=false
DebuggerEventFiltersGameBoy=
GameBoyErrorBreakpointSuspend5=false
GameBoyErrorBreakpointSuspend4=false
GameBoyErrorBreakpointSuspend3=false
DAPExceptionBreakpointFilters=Exception-5\:Break on inconsistent state after interrupt\:false;Exception-4\:Break on read of uninitialized memory\:false;Exception-3\:Break on execution of data\:false;Exception-2\:Break on bank swap at PC\:false;Exception-1\:Break on push to ROM\:false;Exception0\:Break on ld b, b instruction\:false;Exception1\:Break on execution of VRAM\:false;Exception2\:Break on execution of OAM\:false;Exception3\:Break on execution in port address range\:false;Exception9\:Break on write to non-standard MBC address\:false;Exception10\:Break on incorrect cartridge header\:true;Exception4\:Break on access of unusable address range\:false;Exception5\:Break on access of mirror RAM\:false;Exception6\:Break on access of SRAM while inaccessible\:false;Exception16\:Break on access of VRAM while inaccessible\:false;Exception17\:Break on access of Palette while inaccessible\:false;Exception18\:Break on access of OAM while inaccessible\:false;Exception19\:Break on turn off of LCD outside Vblank\:false;Exception8\:Break on bus conflict between CPU and OAM DMA\:false;Exception20\:Break on trigger of OAM bug\:false;Exception7\:Break on trigger of HALT bug\:false;Exception48\:Break on corruption in Wave RAM\:false
GameBoyErrorBreakpointSuspend2=false
GameBoyErrorBreakpointSuspend1=false
GameBoyErrorBreakpointSuspend0=false
GameBoyErrorBreakpointSuspend20=false
WindowDebuggerY=0
WindowDebuggerX=0
GameBoyErrorBreakpointEnabled9=false
DebuggerMemorySelectedAddress=0
UninitializedMemoryBreakpointEnabled=true
GameBoyErrorBreakpointEnabled8=false
GameBoyErrorBreakpointEnabled7=false
GameBoyErrorBreakpointEnabled6=false
GameBoyErrorBreakpointEnabled5=false
GameBoyErrorBreakpointEnabled4=false
GameBoyErrorBreakpointEnabled3=false
WindowEmuliciousY=0
GameBoyErrorBreakpointEnabled2=false
WindowEmuliciousX=0
GameBoyErrorBreakpointEnabled1=false
GameBoyErrorBreakpointEnabled0=false
