#Emulicious settings file
#Mon Oct 05 11:46:15 PDT 2026
Recent0=D\:\\Apps\\coding projects\\gameboy\\checkers\\main.gb
Scale=1.5
AudioSync=false
WindowEmuliciousWidth=300
WindowEmuliciousY=0
WindowEmuliciousX=0
WindowEmuliciousHeight=300
Update=2
FontSize=13
CodeFontSize=13
